config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  resources :products
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, except: %i[index new create]
  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    render layout: "modal"
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: "Product successfully added!"
    else
      render :new, status: :unprocessable_entity, layout: "modal"
    end
  end

  def edit
    render layout: "modal"
  end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: "Product successfully updated!"
    else
      render :edit, status: :unprocessable_entity, layout: "modal"
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: "Product was successfully destroyed."
  end

  private
  def product_params
    params.expect(product: [ :name ])
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_confirm.html.slim
#confirm.confirm-dialog-wrapper
  .confirm-dialog-wrapper__backdrop.confirm-cancel
  .confirm-dialog
    .confirm-dialog__header Are you sure?
    .confirm-dialog__body
      p This action cannot be undone.
    .confirm-dialog__footer
      button.btn.confirm-cancel Cancel
      button#confirm-accept.btn.btn--destructive Yes, I'm sure

app/views/application/_flash.html.slim
#flash data-turbo-temporary="true"
  - flash.each do |type, message|
    .alert.alert--flash class="alert--#{type}" role="alert" data-testid="flash-notification"
      .alert__messages
        .alert__description = message

app/views/application/_head.html.slim
  = csrf_meta_tags
  = csp_meta_tag
  = yield :head

  link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@rolemodel/optics@2.1.3/dist/css/optics.min.css"

  meta name="turbo-refresh-method" content="morph"
  meta name="turbo-refresh-scroll" content="preserve"

  = stylesheet_link_tag :app, 'data-turbo-track': 'reload'
  = javascript_importmap_tags

app/views/layouts/application.html.slim
doctype html
html data-theme-mode="light"
  head = render 'head'
  body
    = render 'flash'
    = render 'confirm'
    = turbo_frame_tag 'modal'
    #app.container
      = yield

app/views/layouts/modal.html.slim
doctype html
html data-theme-mode="light"
  head = render 'head'
  body
    = turbo_frame_tag 'modal' do
      dialog.modal(
        open=(response.message.start_with?('Unprocessable'))
        data-controller="dialog"
      )
        .modal__header
          = yield :modal_header
        .modal__body data-testid="modal-content"
          = yield
        .modal__footer
          = button_tag 'Close', class: 'btn', data: { action: 'dialog#close' }
          = yield :modal_footer

app/views/products/_form.html.slim
-# locals: (model:)

= form_for model do |f|
  .form__group
    = f.label :name
    = f.text_field :name, class: 'form-control'
    = tag.p(f.object.errors[:name].join(', '), class: 'form-error') if f.object.errors[:name].any?

  = content_for :modal_footer do
    = f.submit 'Save', class: 'btn btn--primary', form: f.id

app/views/products/_product.html.slim
-# locals: (product:)

tr data-testid=dom_id(product)
  td = product.name
  td.flex.gap-sm
    = link_to 'Edit', [:edit, product], class: 'btn btn--primary', data: { turbo_frame: 'modal' }
    = button_to 'Delete', product, method: :delete, class: 'btn btn--destructive', data: { turbo_confirm: 'Are you sure?' }

app/views/products/edit.html.slim
= content_for :modal_header do
  h1 Edit Product

= render 'form', model: @product

app/views/products/index.html.slim
- provide(:title, "Products")
.flex.justify-between
  .header__title
    h1 Products
  .header__actions
    = link_to "New Product", new_product_path, class: 'btn', data: { turbo_frame: 'modal' }

table.table
  thead: tr
    th Product
    th Actions
  tbody
    = render @products

app/views/products/new.html.slim
= content_for :modal_header do
  h1 New Product

= render 'form', model: @product